### ISSUE TITLE
How to run on Linux (Ubuntu)

### ISSUE THREAD

**Issue by Qasimmodo** [stigsfoot/pokemongo-hotspots#1]
Could you give instructions on how to run this on Ubuntu?
And also the prerequisites.

**Comment by stigsfoot** [comment]
Good suggestion. I will include that in the readme next.

**Comment by Qasimmodo** [comment]
Thank you.

**Comment by stigsfoot** [comment]
@Qasimmodo I have added the instructions to the README, but please note,  this project is still in development, I only begun a week or so before you posted this. Things may break but feel free to provide feedback.

Thanks,

Noble
